import type {
  AssetRecord,
  AssetSelection,
  ContentBrief,
  LearningRecord,
  OptimizationRecommendation,
  PipelineRun,
  ProductionDirective,
  RenderJob,
  Storyboard,
} from "@/features/kontenai/types";
import { generateId } from "@/features/kontenai/lib/ids";

/**
 * Single shared in-memory "database" for the whole KontenAI pipeline.
 *
 * This is a deliberate mock of what will eventually be Supabase tables:
 * every sprint module reads and writes through this store instead of
 * keeping its own disconnected local array, so a directive generated by
 * AI Director is the same object a Storyboard Engine action can look up,
 * a storyboard built there is what Asset Selector and Render Engine see,
 * and Production Pipeline can orchestrate all of it end-to-end.
 *
 * It resets whenever the server process restarts (no persistence) -- that
 * is expected and acceptable for this build phase. `globalThis` caching
 * only exists to survive Next.js dev-mode hot-reloads without re-seeding
 * on every file save.
 */
export interface KontenAiMockDatabase {
  assets: AssetRecord[];
  contentBriefs: ContentBrief[];
  directives: ProductionDirective[];
  storyboards: Storyboard[];
  assetSelections: AssetSelection[];
  renderJobs: RenderJob[];
  pipelineRuns: PipelineRun[];
  learningRecords: LearningRecord[];
  optimizationRecommendations: OptimizationRecommendation[];
}

declare global {
  var __kontenaiMockDb: KontenAiMockDatabase | undefined;
}

function seedAssets(): AssetRecord[] {
  const now = Date.now();
  const entries: Array<Pick<AssetRecord, "type" | "filename" | "tags" | "sizeBytes" | "durationSeconds"> & { analyzed?: boolean }> = [
    { type: "image", filename: "leasehold-lobby-hero.jpg", tags: ["leasehold_sales", "lobby", "interior", "daylight"], sizeBytes: 2_400_000, durationSeconds: null, analyzed: true },
    { type: "image", filename: "leasehold-unit-livingroom.jpg", tags: ["leasehold_sales", "unit", "livingroom", "modern"], sizeBytes: 1_950_000, durationSeconds: null },
    { type: "video", filename: "leasehold-drone-establishing.mp4", tags: ["leasehold_sales", "drone", "establishing", "exterior"], sizeBytes: 48_000_000, durationSeconds: 22, analyzed: true },
    { type: "video", filename: "villa-pool-sunset.mp4", tags: ["occupancy", "villa", "pool", "sunset"], sizeBytes: 62_000_000, durationSeconds: 18 },
    { type: "image", filename: "villa-bedroom-cozy.jpg", tags: ["occupancy", "villa", "bedroom", "cozy"], sizeBytes: 1_700_000, durationSeconds: null, analyzed: true },
    { type: "video", filename: "villa-guest-testimonial.mp4", tags: ["occupancy", "testimonial", "guest", "closeup"], sizeBytes: 35_000_000, durationSeconds: 14 },
    { type: "image", filename: "beauty-before-after-skin.jpg", tags: ["beauty", "before-after", "skin", "closeup"], sizeBytes: 2_100_000, durationSeconds: null, analyzed: true },
    { type: "video", filename: "beauty-treatment-process.mp4", tags: ["beauty", "process", "treatment", "studio"], sizeBytes: 41_000_000, durationSeconds: 26 },
    { type: "image", filename: "beauty-product-flatlay.jpg", tags: ["beauty", "product", "flatlay", "studio"], sizeBytes: 1_500_000, durationSeconds: null },
    { type: "video", filename: "general-team-culture.mp4", tags: ["general", "team", "culture", "office"], sizeBytes: 30_000_000, durationSeconds: 20 },
    { type: "logo", filename: "mk-connect-logo-white.png", tags: ["logo", "brand", "watermark"], sizeBytes: 120_000, durationSeconds: null, analyzed: true },
    { type: "template", filename: "instagram-reel-caption-template.psd", tags: ["template", "reel", "caption", "instagram"], sizeBytes: 8_500_000, durationSeconds: null },
    { type: "audio", filename: "upbeat-corporate-bg.mp3", tags: ["audio", "upbeat", "background", "corporate"], sizeBytes: 4_200_000, durationSeconds: 45, analyzed: true },
    { type: "audio", filename: "calm-ambient-loop.mp3", tags: ["audio", "ambient", "calm", "loop"], sizeBytes: 3_800_000, durationSeconds: 60 },
  ];

  return entries.map((entry, index) => {
    const id = generateId("asset");
    return {
      id,
      type: entry.type,
      filename: entry.filename,
      url: `https://assets.mock.kontenai.local/${entry.filename}`,
      thumbnailUrl: entry.type === "video" || entry.type === "image" ? `https://assets.mock.kontenai.local/thumbs/${entry.filename}.jpg` : null,
      sizeBytes: entry.sizeBytes,
      durationSeconds: entry.durationSeconds,
      tags: entry.tags,
      uploadedAt: new Date(now - index * 6 * 60 * 60 * 1000).toISOString(),
      uploadedBy: "system-seed",
      metadata: entry.analyzed
        ? {
            assetId: id,
            description: `Aset ${entry.type} bertema ${entry.tags[1] ?? entry.tags[0]}, siap dipakai untuk konten ${entry.tags[0]}.`,
            detectedObjects: entry.tags.slice(1, 4),
            dominantColors: ["#1f2937", "#f5f5f4", "#a16207"],
            qualityScore: 7 + (index % 3),
            suggestedUseCases: ["hook", "supporting_shot", "closing_shot"],
            analyzedAt: new Date(now - index * 5 * 60 * 60 * 1000).toISOString(),
          }
        : null,
    };
  });
}

function seedContentBriefs(): ContentBrief[] {
  const now = Date.now();
  const entries: Array<Pick<ContentBrief, "title" | "description" | "contentFocus" | "targetPlatform"> & { withAudit?: boolean }> = [
    { title: "Promo Unit Ready Stock Leasehold Q3", description: "Dorong konversi unit ready stock dengan urgensi harga.", contentFocus: "leasehold_sales", targetPlatform: "instagram", withAudit: true },
    { title: "Highlight Fasilitas Klub House", description: "Perkenalkan fasilitas premium untuk calon penyewa.", contentFocus: "leasehold_sales", targetPlatform: "tiktok" },
    { title: "Weekend Getaway di Villa Cariu", description: "Ajak audiens booking akhir pekan dengan nuansa relax.", contentFocus: "occupancy", targetPlatform: "instagram", withAudit: true },
    { title: "Testimoni Tamu Villa Puncak", description: "Bangun kepercayaan lewat cerita tamu asli.", contentFocus: "occupancy", targetPlatform: "tiktok" },
    { title: "Before-After Treatment Glow Skin", description: "Tunjukkan hasil nyata treatment andalan.", contentFocus: "beauty", targetPlatform: "instagram", withAudit: true },
    { title: "Edukasi Rangkaian Produk Skincare", description: "Edukasi audiens soal urutan pemakaian produk.", contentFocus: "beauty", targetPlatform: "tiktok" },
    { title: "Budaya Kerja Tim Markom", description: "Konten culture untuk employer branding.", contentFocus: "general", targetPlatform: "instagram" },
    { title: "Rekap Pencapaian Kuartal", description: "Rangkum pencapaian tim ke publik secara ringan.", contentFocus: "general", targetPlatform: "tiktok", withAudit: true },
  ];

  return entries.map((entry, index) => ({
    id: generateId("brief"),
    kpiTaskId: generateId("kpi_task"),
    title: entry.title,
    description: entry.description,
    contentFocus: entry.contentFocus,
    targetPlatform: entry.targetPlatform,
    branchId: generateId("branch"),
    divisionId: generateId("division"),
    dueDate: new Date(now + (index + 1) * 2 * 24 * 60 * 60 * 1000).toISOString(),
    auditInsight: entry.withAudit
      ? {
          narrative: `Performa konten ${entry.contentFocus} minggu lalu solid di hook, perlu penguatan di CTA.`,
          scores: {
            hook: 7.8,
            value: 7.2,
            cta: 6.4,
            nicheFit: 8.1,
            engagementPotential: 7.5,
            platformOptimization: 7.0,
            overall: 7.3,
          },
          growthSignal: index % 2 === 0 ? "on_track" : "excellent",
          recommendations: ["Perkuat CTA dengan urgensi waktu", "Coba durasi lebih pendek di 15 detik pertama"],
        }
      : null,
  }));
}

function createMockDb(): KontenAiMockDatabase {
  return {
    assets: seedAssets(),
    contentBriefs: seedContentBriefs(),
    directives: [],
    storyboards: [],
    assetSelections: [],
    renderJobs: [],
    pipelineRuns: [],
    learningRecords: [],
    optimizationRecommendations: [],
  };
}

export function getMockDb(): KontenAiMockDatabase {
  if (!globalThis.__kontenaiMockDb) {
    globalThis.__kontenaiMockDb = createMockDb();
  }
  return globalThis.__kontenaiMockDb;
}

export function findAssetById(id: string): AssetRecord | undefined {
  return getMockDb().assets.find((asset) => asset.id === id);
}

export function findContentBriefById(id: string): ContentBrief | undefined {
  return getMockDb().contentBriefs.find((brief) => brief.id === id);
}

export function findDirectiveById(id: string): ProductionDirective | undefined {
  return getMockDb().directives.find((directive) => directive.id === id);
}

export function findStoryboardById(id: string): Storyboard | undefined {
  return getMockDb().storyboards.find((storyboard) => storyboard.id === id);
}

export function findRenderJobById(id: string): RenderJob | undefined {
  return getMockDb().renderJobs.find((job) => job.id === id);
}

export function findPipelineRunById(id: string): PipelineRun | undefined {
  return getMockDb().pipelineRuns.find((run) => run.id === id);
}
