/**
 * Roles are data-driven (stored in the `roles` table), not a hardcoded enum,
 * so new roles can be added without a schema or code change. These keys are
 * the seed set for v1 and are used only as typed references in app code /
 * seed data — the source of truth at runtime is always the database row.
 */
export const ROLE_KEYS = {
  SUPER_ADMIN: "super_admin",
  DIREKTUR_UTAMA: "direktur_utama",
  DIREKTUR_OPERASIONAL: "direktur_operasional",
  HR: "hr",
  KEPALA_CABANG: "kepala_cabang",
  MANAGER: "manager",
  STAFF: "staff",
  SALES: "sales",
  FINANCE: "finance",
  /** Placeholder role for self-registered accounts awaiting approval — grants nothing. */
  PENDING: "pending",
} as const;

export type RoleKey = (typeof ROLE_KEYS)[keyof typeof ROLE_KEYS];

/**
 * Permission keys follow `<resource>.<action>` and are additive: a role has
 * a permission if it exists in role_permissions. Scope (own / branch / all)
 * is resolved separately via RLS + branch_id comparison, not encoded here.
 */
export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",

  ATTENDANCE_VIEW_OWN: "attendance.view_own",
  ATTENDANCE_VIEW_BRANCH: "attendance.view_branch",
  ATTENDANCE_VIEW_ALL: "attendance.view_all",
  ATTENDANCE_MANAGE: "attendance.manage",
  ATTENDANCE_SETTINGS_MANAGE: "attendance.settings_manage",
  ATTENDANCE_EXPORT: "attendance.export",

  MEMO_VIEW: "memo.view",
  MEMO_CREATE: "memo.create",
  MEMO_MANAGE: "memo.manage",

  ANNOUNCEMENT_VIEW: "announcement.view",
  ANNOUNCEMENT_CREATE: "announcement.create",
  ANNOUNCEMENT_MANAGE: "announcement.manage",

  EMPLOYEE_VIEW_BRANCH: "employee.view_branch",
  EMPLOYEE_VIEW_ALL: "employee.view_all",
  EMPLOYEE_MANAGE: "employee.manage",

  BRANCH_MANAGE: "branch.manage",
  DIVISION_MANAGE: "division.manage",
  POSITION_MANAGE: "position.manage",
  ROLE_MANAGE: "role.manage",

  SETTINGS_MANAGE: "settings.manage",
  AUDIT_LOG_VIEW: "audit_log.view",
  SYSTEM_MONITORING_VIEW: "system.monitoring_view",

  REGISTRATION_VIEW_ALL: "registration.view_all",
  REGISTRATION_VIEW_BRANCH: "registration.view_branch",
  REGISTRATION_MANAGE: "registration.manage",

  PROSPECT_VIEW_OWN: "prospect.view_own",
  PROSPECT_VIEW_BRANCH: "prospect.view_branch",
  PROSPECT_VIEW_ALL: "prospect.view_all",
  PROSPECT_CREATE: "prospect.create",
  PROSPECT_MANAGE: "prospect.manage",
  PROSPECT_FOLLOW_UP_CREATE: "prospect.follow_up_create",
  PROSPECT_FINANCE_VERIFY: "prospect.finance_verify",

  SALES_TARGET_VIEW_OWN: "sales_target.view_own",
  SALES_TARGET_VIEW_BRANCH: "sales_target.view_branch",
  SALES_TARGET_VIEW_ALL: "sales_target.view_all",
  SALES_TARGET_MANAGE: "sales_target.manage",

  CRM_ANALYTICS_VIEW_BRANCH: "crm_analytics.view_branch",
  CRM_ANALYTICS_VIEW_ALL: "crm_analytics.view_all",
  CRM_PROJECT_MANAGE: "crm_project.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Seed mapping of role -> permissions, mirrored in supabase/seed/02_rbac_seed.sql */
export const ROLE_PERMISSIONS_SEED: Record<RoleKey, PermissionKey[]> = {
  [ROLE_KEYS.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLE_KEYS.DIREKTUR_UTAMA]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_EXPORT,
    PERMISSIONS.MEMO_VIEW,
    PERMISSIONS.MEMO_CREATE,
    PERMISSIONS.MEMO_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.EMPLOYEE_VIEW_ALL,
    PERMISSIONS.EMPLOYEE_MANAGE,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.DIVISION_MANAGE,
    PERMISSIONS.POSITION_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.PROSPECT_VIEW_ALL,
    PERMISSIONS.PROSPECT_MANAGE,
    PERMISSIONS.SALES_TARGET_VIEW_ALL,
    PERMISSIONS.SALES_TARGET_MANAGE,
    PERMISSIONS.CRM_ANALYTICS_VIEW_ALL,
    PERMISSIONS.CRM_PROJECT_MANAGE,
  ],
  [ROLE_KEYS.DIREKTUR_OPERASIONAL]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_SETTINGS_MANAGE,
    PERMISSIONS.ATTENDANCE_EXPORT,
    PERMISSIONS.MEMO_VIEW,
    PERMISSIONS.MEMO_CREATE,
    PERMISSIONS.MEMO_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.EMPLOYEE_VIEW_ALL,
    PERMISSIONS.EMPLOYEE_MANAGE,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.DIVISION_MANAGE,
    PERMISSIONS.POSITION_MANAGE,
    PERMISSIONS.REGISTRATION_VIEW_ALL,
    PERMISSIONS.REGISTRATION_MANAGE,
    PERMISSIONS.PROSPECT_VIEW_ALL,
    PERMISSIONS.SALES_TARGET_VIEW_ALL,
    PERMISSIONS.CRM_ANALYTICS_VIEW_ALL,
    PERMISSIONS.CRM_PROJECT_MANAGE,
  ],
  // HR administers people and attendance company-wide but must not be able
  // to restructure the org chart (branches/divisions/positions) or touch
  // roles/settings — those stay with Direktur Utama/Operasional.
  [ROLE_KEYS.HR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_SETTINGS_MANAGE,
    PERMISSIONS.ATTENDANCE_EXPORT,
    PERMISSIONS.MEMO_VIEW,
    PERMISSIONS.MEMO_CREATE,
    PERMISSIONS.MEMO_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.EMPLOYEE_VIEW_ALL,
    PERMISSIONS.EMPLOYEE_MANAGE,
  ],
  [ROLE_KEYS.KEPALA_CABANG]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_BRANCH,
    PERMISSIONS.ATTENDANCE_EXPORT,
    PERMISSIONS.MEMO_VIEW,
    PERMISSIONS.MEMO_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.ANNOUNCEMENT_CREATE,
    PERMISSIONS.EMPLOYEE_VIEW_BRANCH,
    PERMISSIONS.REGISTRATION_VIEW_BRANCH,
    PERMISSIONS.REGISTRATION_MANAGE,
    PERMISSIONS.PROSPECT_VIEW_BRANCH,
    PERMISSIONS.PROSPECT_FOLLOW_UP_CREATE,
    PERMISSIONS.SALES_TARGET_VIEW_BRANCH,
    PERMISSIONS.CRM_ANALYTICS_VIEW_BRANCH,
  ],
  [ROLE_KEYS.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_BRANCH,
    PERMISSIONS.MEMO_VIEW,
    PERMISSIONS.MEMO_CREATE,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW_BRANCH,
  ],
  [ROLE_KEYS.STAFF]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.MEMO_VIEW,
    PERMISSIONS.ANNOUNCEMENT_VIEW,
  ],
  [ROLE_KEYS.SALES]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROSPECT_VIEW_OWN,
    PERMISSIONS.PROSPECT_CREATE,
    PERMISSIONS.PROSPECT_FOLLOW_UP_CREATE,
    PERMISSIONS.SALES_TARGET_VIEW_OWN,
  ],
  [ROLE_KEYS.FINANCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROSPECT_VIEW_ALL,
    PERMISSIONS.PROSPECT_FINANCE_VERIFY,
    PERMISSIONS.CRM_ANALYTICS_VIEW_ALL,
  ],
  [ROLE_KEYS.PENDING]: [],
};
