-- ============================================================================
-- MK Connect — 0169: KontenAI full automation (toggle-gated)
--
-- Adds an owner-controlled on/off switch (kontenai_automation_settings,
-- single row) for a daily pipeline: pending kpi_tasks (occupancy/
-- leasehold_sales/beauty, already generated by the existing Markom AI
-- checklist automation) are turned into a Creative Brief -> Storyboard ->
-- Asset Selection -> Render Job automatically, and once a render completes
-- it's bridged into Content Studio for AI review, auto-schedule (score >=
-- 8.5), and auto-publish (existing publish worker), which already deletes
-- the video from storage on successful publish.
--
-- kontenai_creative_briefs.kpi_task_id links an automation-originated brief
-- back to the kpi_task that spawned it -- both to avoid double-producing the
-- same task and to let the Render/Studio bridge trace back to it. A partial
-- unique index enforces "at most one automated brief per task" at the DB
-- level, not just in application logic (two concurrent cron ticks could
-- otherwise both claim the same task).
--
-- Everything here is off by default (kontenai_automation_settings.enabled =
-- false) -- the dispatch functions below check it first and no-op instead of
-- enqueueing anything while off.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- kontenai_automation_settings: single-row toggle. Uses a fixed text id
-- ('singleton') rather than a real key, matching the one-row-only intent --
-- app_is_super_admin() write policy so only Super Admin can flip it from the
-- KontenAI page's toggle.
-- ----------------------------------------------------------------------------
create table public.kontenai_automation_settings (
  id text primary key default 'singleton' check (id = 'singleton'),
  enabled boolean not null default false,
  updated_by uuid references public.employees(id),
  updated_at timestamptz not null default now()
);
alter table public.kontenai_automation_settings enable row level security;

insert into public.kontenai_automation_settings (id, enabled) values ('singleton', false);

create policy kontenai_automation_settings_select on public.kontenai_automation_settings
  for select using (app_is_super_admin());

create policy kontenai_automation_settings_write on public.kontenai_automation_settings
  for update using (app_is_super_admin()) with check (app_is_super_admin());

comment on table public.kontenai_automation_settings is
  'Single-row on/off switch for the full daily KontenAI automation (brief -> render -> Content Studio -> publish -> storage cleanup). Off by default. Super Admin only.';

-- ----------------------------------------------------------------------------
-- kontenai_creative_briefs.kpi_task_id: links an automation-originated brief
-- back to its source kpi_task. Nullable -- manually-created briefs (AI
-- Director UI) never set this.
-- ----------------------------------------------------------------------------
alter table public.kontenai_creative_briefs
  add column kpi_task_id uuid references public.kpi_tasks(id);

create unique index kontenai_creative_briefs_kpi_task_id_unique
  on public.kontenai_creative_briefs (kpi_task_id)
  where kpi_task_id is not null;

-- ----------------------------------------------------------------------------
-- markom_content_submissions: at most one non-deleted submission per
-- kpi_task, so the Content Studio bridge job can never double-submit the
-- same task's render output even under concurrent dispatch.
-- ----------------------------------------------------------------------------
create unique index markom_content_submissions_task_id_unique
  on public.markom_content_submissions (task_id)
  where task_id is not null and deleted_at is null;

-- ----------------------------------------------------------------------------
-- ai_job_queue: two new job types for the automation pipeline.
-- ----------------------------------------------------------------------------
alter table public.ai_job_queue drop constraint ai_job_queue_job_type_check;
alter table public.ai_job_queue add constraint ai_job_queue_job_type_check check (job_type in (
  'whatsapp_ai_reply',
  'crm_sp1_draft',
  'markom_checklist_draft',
  'meta_ads_launch',
  'meta_ads_research',
  'social_weekly_evaluation',
  'crm_sales_coaching',
  'loonars_beauty_weekly_evaluation',
  'knowledge_bank_refresh',
  'sales_closing_tips_broadcast',
  'leasehold_competitor_comparison',
  'competitor_discovery',
  'loonars_beauty_competitor_comparison',
  'loonars_beauty_content_ideas_draft',
  'investor_intelligence_refresh',
  'cashflow_intelligence_refresh',
  'sales_teaching_weekly',
  'cashflow_action_plan',
  'loonars_beauty_weekly_content_audit',
  'markom_content_performance_broadcast',
  'occupancy_intelligence_refresh',
  'occupancy_teaching_biweekly',
  'content_submission_review',
  'kontenai_auto_produce',
  'kontenai_auto_bridge_to_studio'
));

-- ----------------------------------------------------------------------------
-- kontenai_automation_dispatch: pg_cron sweep (every 5 minutes). No-ops
-- entirely unless kontenai_automation_settings.enabled is true. Two things
-- to dispatch each tick, both small batches so one tick never floods the
-- Gemini/render pipeline:
--  1. Pending kpi_tasks (occupancy/leasehold_sales/beauty, not yet linked to
--     an automation brief) -> enqueue kontenai_auto_produce.
--  2. Completed kontenai_render_jobs whose storyboard traces back to an
--     automation brief, and whose kpi_task has no Content Studio submission
--     yet -> enqueue kontenai_auto_bridge_to_studio.
-- ----------------------------------------------------------------------------
create or replace function public.kontenai_automation_dispatch()
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_enabled boolean;
  v_row record;
begin
  select enabled into v_enabled from public.kontenai_automation_settings where id = 'singleton';
  if not coalesce(v_enabled, false) then
    return;
  end if;

  -- 1. New briefs to produce.
  for v_row in
    select t.id
    from public.kpi_tasks t
    where t.status = 'pending'
      and t.deleted_at is null
      and t.content_focus in ('occupancy', 'leasehold_sales', 'beauty')
      and not exists (select 1 from public.kontenai_creative_briefs b where b.kpi_task_id = t.id)
    order by t.created_at
    limit 5
  loop
    insert into public.ai_job_queue (job_type, payload)
    values ('kontenai_auto_produce', jsonb_build_object('kpi_task_id', v_row.id));
  end loop;

  -- 2. Completed renders to bridge into Content Studio.
  for v_row in
    select rj.id
    from public.kontenai_render_jobs rj
    join public.kontenai_storyboards sb on sb.id = rj.storyboard_id
    join public.kontenai_creative_briefs b on b.id = sb.creative_brief_id
    where rj.status = 'completed'
      and b.kpi_task_id is not null
      and not exists (
        select 1 from public.markom_content_submissions s
        where s.task_id = b.kpi_task_id and s.deleted_at is null
      )
    order by rj.completed_at
    limit 5
  loop
    insert into public.ai_job_queue (job_type, payload)
    values ('kontenai_auto_bridge_to_studio', jsonb_build_object('render_job_id', v_row.id));
  end loop;
end;
$$;

grant execute on function public.kontenai_automation_dispatch() to service_role;

select cron.schedule('kontenai-automation-dispatch', '*/5 * * * *', $$select public.kontenai_automation_dispatch();$$);
