-- ============================================================================
-- MK Connect — 0251: Markom AI gap-closers (monthly report, hashtag bank)
--
-- Two of the AI-feasible gaps identified in a review of the Markom module
-- against a "Social Media Specialist" role, both following existing
-- patterns exactly (no new architecture):
--
-- 1. social_monthly_content_reports -- a monthly rollup of the weekly
--    content audits that already exist (social_weekly_evaluations,
--    0111/0124). Growth numbers (follower growth %, avg weekly score,
--    best/worst week) are computed in application code from real data,
--    never by the model -- same "numbers in code, AI narrates" rule
--    already enforced for FRIDAY (lib/ai/friday/signals.ts). Property only
--    (leasehold_sales + occupancy share one account) for this first pass,
--    same scope weekly evaluation itself started at (0111) before Beauty
--    got its own version later (0133) -- Beauty can follow the same path
--    if/when there's a need.
--
-- 2. markom_hashtag_bank -- AI-generated hashtag sets per content_focus x
--    platform, following the 30/40/30 broad/medium/niche formula already
--    documented in the markom system prompt (lib/ai/domains/prompts.ts).
--    Regenerated by replacing the focus+platform's rows wholesale (not
--    accumulated) so the bank never grows stale/duplicated -- a fresh
--    weekly run is a clean slate, not a merge.
-- ============================================================================

create table public.social_monthly_content_reports (
  id uuid primary key default gen_random_uuid(),
  month_start date not null,
  report jsonb not null,
  narrative text not null,
  created_at timestamptz not null default now()
);
create unique index social_monthly_content_reports_month_start_key on public.social_monthly_content_reports (month_start);

alter table public.social_monthly_content_reports enable row level security;
create policy social_monthly_content_reports_select on public.social_monthly_content_reports for select to authenticated
  using (public.app_has_permission('content_planner.view'));

-- ----------------------------------------------------------------------------
-- markom_hashtag_bank: AI-generated, wholesale-replaced per (content_focus,
-- platform) on each refresh -- see replaceHashtagBank
-- (repositories/social.repository.ts). Same content_focus split/permission
-- pattern as social_competitor_accounts (0125): beauty gated by
-- loonars_beauty.*, leasehold_sales/occupancy by content_planner.*.
-- ----------------------------------------------------------------------------
create table public.markom_hashtag_bank (
  id uuid primary key default gen_random_uuid(),
  content_focus text not null check (content_focus in ('leasehold_sales', 'occupancy', 'beauty')),
  platform text not null check (platform in ('instagram', 'tiktok')),
  tier text not null check (tier in ('broad', 'medium', 'niche')),
  hashtag text not null,
  rationale text,
  generated_at timestamptz not null default now()
);
create index markom_hashtag_bank_focus_platform_idx on public.markom_hashtag_bank (content_focus, platform);

alter table public.markom_hashtag_bank enable row level security;
create policy markom_hashtag_bank_select on public.markom_hashtag_bank for select to authenticated
  using (
    (content_focus = 'beauty' and public.app_has_permission('loonars_beauty.view'))
    or (content_focus <> 'beauty' and public.app_has_permission('content_planner.view'))
  );
create policy markom_hashtag_bank_write on public.markom_hashtag_bank for all to authenticated
  using (
    (content_focus = 'beauty' and public.app_has_permission('loonars_beauty.manage'))
    or (content_focus <> 'beauty' and public.app_has_permission('content_planner.manage'))
  )
  with check (
    (content_focus = 'beauty' and public.app_has_permission('loonars_beauty.manage'))
    or (content_focus <> 'beauty' and public.app_has_permission('content_planner.manage'))
  );

-- ----------------------------------------------------------------------------
-- ai_job_queue gains the two job types these features dispatch through.
-- ----------------------------------------------------------------------------
alter table public.ai_job_queue drop constraint ai_job_queue_job_type_check;
alter table public.ai_job_queue add constraint ai_job_queue_job_type_check check (job_type in (
  'whatsapp_ai_reply',
  'crm_sp1_draft',
  'markom_checklist_draft',
  'meta_ads_launch',
  'meta_ads_research',
  'social_weekly_evaluation',
  'crm_sales_coaching',
  'loonars_beauty_weekly_evaluation',
  'knowledge_bank_refresh',
  'sales_closing_tips_broadcast',
  'leasehold_competitor_comparison',
  'competitor_discovery',
  'loonars_beauty_competitor_comparison',
  'loonars_beauty_content_ideas_draft',
  'investor_intelligence_refresh',
  'cashflow_intelligence_refresh',
  'sales_teaching_weekly',
  'cashflow_action_plan',
  'loonars_beauty_weekly_content_audit',
  'markom_content_performance_broadcast',
  'occupancy_intelligence_refresh',
  'occupancy_teaching_biweekly',
  'content_submission_review',
  'kontenai_auto_produce',
  'kontenai_auto_bridge_to_studio',
  'zernio_publish_reconcile',
  'friday_executive_briefing',
  'friday_holding_briefing',
  'kontenai_asset_vision',
  'kontenai_auto_produce_beauty',
  'whatsapp_lead_nurture_reply',
  'whatsapp_admin_answer_relay',
  -- This migration
  'social_monthly_content_report',
  'markom_hashtag_bank_refresh'
));

-- ----------------------------------------------------------------------------
-- Monthly report: automatic on the 1st of each month (covers the just-
-- completed month), plus an on-demand manual trigger.
-- ----------------------------------------------------------------------------
create or replace function public.social_run_monthly_report_dispatch()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.ai_job_queue (job_type, payload) values ('social_monthly_content_report', '{}'::jsonb);
end;
$$;

select cron.schedule('social-monthly-content-report', '0 1 1 * *', $$select public.social_run_monthly_report_dispatch();$$);

create or replace function public.markom_request_monthly_report()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.app_has_permission('content_planner.manage') then
    raise exception 'permission denied';
  end if;

  insert into public.ai_job_queue (job_type, payload) values ('social_monthly_content_report', '{}'::jsonb);
end;
$$;

grant execute on function public.markom_request_monthly_report() to authenticated;

-- ----------------------------------------------------------------------------
-- Hashtag bank: automatic weekly refresh for all 3 foci x 2 platforms, plus
-- an on-demand manual trigger per focus+platform (mirrors
-- markom_request_competitor_discovery, 0125).
-- ----------------------------------------------------------------------------
create or replace function public.markom_run_hashtag_bank_dispatch()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_focus text;
  v_platform text;
begin
  foreach v_focus in array array['leasehold_sales', 'occupancy', 'beauty'] loop
    foreach v_platform in array array['instagram', 'tiktok'] loop
      insert into public.ai_job_queue (job_type, payload) values ('markom_hashtag_bank_refresh', jsonb_build_object('focus', v_focus, 'platform', v_platform));
    end loop;
  end loop;
end;
$$;

select cron.schedule('markom-hashtag-bank-dispatch-weekly', '0 2 * * 0', $$select public.markom_run_hashtag_bank_dispatch();$$);

create or replace function public.markom_request_hashtag_bank_refresh(p_focus text, p_platform text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_focus not in ('leasehold_sales', 'occupancy', 'beauty') then
    raise exception 'invalid focus: %', p_focus;
  end if;
  if p_platform not in ('instagram', 'tiktok') then
    raise exception 'invalid platform: %', p_platform;
  end if;

  if p_focus = 'beauty' then
    if not public.app_has_permission('loonars_beauty.manage') then
      raise exception 'permission denied';
    end if;
  else
    if not public.app_has_permission('content_planner.manage') then
      raise exception 'permission denied';
    end if;
  end if;

  insert into public.ai_job_queue (job_type, payload) values ('markom_hashtag_bank_refresh', jsonb_build_object('focus', p_focus, 'platform', p_platform));
end;
$$;

grant execute on function public.markom_request_hashtag_bank_refresh(text, text) to authenticated;
